import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import useStateModal from '../src/hooks/useStateModal';
import useRecoilModal from '../src/hooks/useRecoilModal';
import modalState from '../src/store/modal';
import { useRecoilValue } from 'recoil';

const StateModal = ({ isModalOpened }: { isModalOpened: boolean }) => {
  return (
    <>
      {isModalOpened && (
        <div
          style={{
            top: 50,
            left: 50,
            width: 300,
            height: 300,
            position: 'absolute',
            backgroundColor: 'green',
          }}
        >
          state modal
        </div>
      )}
    </>
  );
};

const StoreModal = () => {
  const isModalOpened = useRecoilValue(modalState);
  return (
    <>
      {isModalOpened && (
        <div
          style={{
            top: 50,
            left: 380,
            width: 300,
            height: 300,
            position: 'absolute',
            backgroundColor: 'red',
          }}
        >
          state modal
        </div>
      )}
    </>
  );
};

const Contents = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </>
  );
};

const Home: NextPage = () => {
  const { modal, setModal: setStateModal } = useStateModal();
  const { setModal } = useRecoilModal();
  return (
    <div className={styles.container} style={{ backgroundColor: 'black' }}>
      <button onClick={() => setStateModal((state) => !state)}>
        onclick state
      </button>
      <button onClick={() => setModal((state) => !state)}>
        onclick recoil store
      </button>
      <StateModal isModalOpened={modal} />
      <StoreModal />
      <Contents />
    </div>
  );
};

export default Home;
